default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: gulshan
  host: localhost
  port: 5432

development:
  <<: *default
  database: sunspree_dev

test:
  <<: *default
  database: sunspree_test

# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
